server:
  port: 8080

spring.h2.console.enabled: true

spring:
  application:
    name: reservation-service
  h2:
    console:
      path: /h2-console
      enabled: true

  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    ddl-auto: create
    show-sql: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
