server:
  port: 8081

spring.h2.console.enabled: true

spring:
  application:
    name: reservation-service
  h2:
    console:
      path: /h2-console
      enabled: true

  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup
      enable-auto-commit: false
      auto-offset-reset: latest
    listener:
      ack-mode: manual
