server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ROOM?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 12312541
  jpa:
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup
      enable-auto-commit: false
      auto-offset-reset: latest
    listener:
      ack-mode: manual