server:
  port: 8083

spring:
  cloud:
    stream:
      bindings:
        room-event-in:
          destination: room-event
          group: consumer-group-1
        room-event-out:
          destination: review-event
          group: consumer-group-1
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            auto.offset.reset: earliest
            key.deserialize: org.apache.kafka.common.serialization.StringDeserializer
            value.deserialize: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ROOM?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: sorksnrn12
  jpa:
    show-sql: true