server:
  port: 8083

spring:
  application:
    name: room-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ROOM?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: cindia3704
  jpa:
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup
      enable-auto-commit: false
      auto-offset-reset: latest
    listener:
      ack-mode: manual

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka