spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:h2:~/test2
    driver-class-name: org.h2.Driver
    username: sa

  h2:
    console:
      path: /h2-console
      enabled: true


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

server:
  port: 9000

