spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:h2:~/test
    username: kim
    driver-class-name: org.h2.Driver
    password: kw630916

  h2:
    console:
      path: /h2-console
      enabled: true
server:
  port: 8083