spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:h2:~/test
    username: kim
    driver-class-name: org.h2.Driver
    password: kw630916

  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
